addons:
  sauce_connect: true
language: node_js
node_js:
- '6.7'
cache:
  directories: node_modules
install: npm install --registry=https://registry.npmjs.org/
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: RKMHJ22wLqQS4+/IFV3le4uewJDGPjLZWpNBFWVgcK2pjYnM2ztdfJP9HC5LtAOEWws/At7xDBUhMIuAmgmtSLsT1NTOzZzeiX7YlWVVpJMcXDwTBk31Rm5qUkeDtKCz19Q1YtvbljAl1l6N6SQGJg43BLFYVcP1j+XjyUVVWDhLA12zmVwEVej/HTLsgb23lcf3frUuYTmrgwUGcxYcNu3EymovBLtRUqpZ4ALuMba9XqAPdyQs8RYCJoiUvg92SxR7WV0NIsgs4dHSpJBUwCvIwAXRtZXyURz42JSCEqcZ9vGmkLlrISWZ3I26blTwbNrHDpZhZTb+5IQaWN/0H8/lGI0HQ+cMfr3h1tQ4KGB4SYb9ccS2mb8rK0P3q6nhZl8c9mj3FCTxxRqI7woTb9cwcU8Jprm4+hP44khZS9OIzs/Rf4eNAVD6rl5m8WYj5FytnwxGG4510Bjd3LFDDQ4yqrwYyRc0XY2kU+Eo2GN5YA54jY2vYqtI6onG9k7WkFPC8RCMg43DRCPzMS700oby8fyich5O16Vz5wuVlds+cVElwyZTzFVW5QL2sshwcwr1OOWrpjmIBby1xEdvkKvydPfE+boMKBC1iIQ8kNvPLOXNLIpobjPBQkLaKHsUSSRnSL4KtTbpUQqjOmr3MNbtbN88SEHxLkeurfgjGAw=
  - secure: hJHjAX0h11pdIYuuhba8uEdJjaqCbSMfofQJJQSg72TSz4e8oAGGUeAOfgWJTQHILlB1+W+eTAFnxoChRMWfi7QhzEpeKl+LuPE9UkaFqFRVn3vvaIxrS9XClIFyN3r04o2mILuUt4U1dy9auz1cllgwS0cxf454GBZLhnpDss9DyqoDTdrUmV+nPE4qJJk5hjX4wkRtiL85j11Jhqtqfkl2Th1GsjiFyvvw05dNiF2MgPCzz7v26XG/d6LfGOo7T/bvLNN4/doCID0Soof86K0kuPnUiSBQH+imGDLdTdAvsLehjTmgfUuvazoUvYeWJd0dyP0pi30nd0igrEkxnTmIF1S55/6RqnYTeEKWKy1y4UcxaxwEsDJxsEuJ/gBJB49z+j9L+vCRb/TudRtUNIczBNjTW4I4uH47SQcuuRAjwUNZGMHRZqr0QG2mYR/88ui4NqhZk8zzY1stxEpvfjHhbebzeScHK/DPRlhIVYwcEjuaEZPz879y5cTjFMMA3rmUNfjl/I3mglz7RV0lzfctuMI01GT1HpewAMIVZfNtNVqHwMDikgcfSgySTJp2DrSKUbMFTaxUMKBf4xRpaT3FIY/axs5aHUpZJOOCVW/t/MGOjrWnOM0RA+8+5ivqGfCRYZ6ONBR/SIOwDKyHkw4gbB7JE3oZg/fgOi9m2zw=
