addons:
  sauce_connect: true

language: node_js

node_js:
  - "6.7"

cache:
  directories: node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_fa7429df19ad_key -iv $encrypted_fa7429df19ad_iv -in .env.enc -out ./.env -d

after_success:
  - bash <(curl -s https://codecov.io/bash)
